name: GitHub Actions Discord Webhook
description: Sends the build status to a Discord webhook
inputs:
  webhook_url:
    description: The Discord webhook url
    required: true
  status:
    description: The build status
    required: false
    default: ${{ job.status }}
runs:
  using: composite
  steps:
    - run: $GITHUB_ACTION_PATH/send.sh
      shell: bash
      env:
        WEBHOOK_URL: ${{ inputs.webhook_url }}
        BUILD_STATUS: ${{ inputs.status }}
