name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: nebularg/actions-discord-webhook@master
      with:
        webhook_url: ${{ secrets.discord_webhook_url }}
        status: ${{ job.status }}

    - name: Dump env
      run: set -o posix; set
